import type { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import styles from "../../styles/Home.module.css";
import Footer from "@components/organisms/Footer/Footer";
import Header from "@components/organisms/Header/Header";
import Page from "@components/templates/Privacy/Page";

const Thanks: NextPage = () => {
    const router = useRouter();
    const { app } = router.query;

    return (
        <div>
            <Head>
                <title>memoir</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <Page app />
            </main>
        </div>
    );
};

export default Thanks;
