import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Footer from "@components/organisms/Footer/Footer";
import Header from "@components/organisms/Header/Header";
import Page from "@components/templates/Top/Page";

const Home: NextPage = () => {
    return (
        <div className={styles.container}>
            <Head>
                <title>memoir</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <header className={styles.header}>
                <Header />
            </header>

            <main className={styles.main}>
                <Page />
            </main>

            <footer className={styles.footer}>
                <Footer />
            </footer>
        </div>
    );
};

export default Home;
